### ISSUE TITLE
Reversing a Queue in Python

### ISSUE THREAD

**Issue by Srishti2703** [Sangwan5688/Hacktoberfest2021#1819]
The purpose of this issue is to implement a Python function that reverses the elements of a given queue. Reversing a queue is a common data structure manipulation task and can be a valuable addition to our Python project.

The benefits of implementing this feature are as follows:

Improved functionality: Users can easily reverse the order of elements in a queue, which can be useful in various applications.
Enhanced codebase: The addition of this feature can make our Python project more versatile and user-friendly.
Learning opportunity: This issue provides an opportunity for contributors to practice data structure manipulation in Python.

**Comment by pawan-xdd** [comment]
`from queue import Queue

def reverse_queue(input_queue):
   
    # Create a temporary stack to store elements
    stack = []
    
    # Pop elements from the queue and push them into the stack
    while not input_queue.empty():
        item = input_queue.get()
        stack.append(item)
    
    # Pop elements from the stack and enqueue them back to the queue
    while stack:
        item = stack.pop()
        input_queue.put(item)
    
    return input_queue

# Example usage:
if __name__ == "__main__":
    # Create a sample queue
    sample_queue = Queue()
    for x in range(1,5):
        sample_queue.put(x)
    #This will do the following
    #sample_queue.put(1)
    #sample_queue.put(2)
    #sample_queue.put(3)
    #sample_queue.put(4)
    
    print("Original Queue:")
    print(list(sample_queue.queue))  # Output: [1, 2, 3, 4]
    
    # Reverse the queue
    reversed_queue = reverse_queue(sample_queue)
    
    print("Reversed Queue:")
    print(list(reversed_queue.queue))  # Output: [4, 3, 2, 1]
`

**Comment by DevanshKyada27** [comment]
Hey @Sangwan5688 can please assign this issue to me. Want to work on it.
