### ISSUE TITLE
Github Automation script

### ISSUE THREAD

**Issue by CodeBurnerProgramming** [Sangwan5688/Hacktoberfest2021#2066]
I am new to Git and Github and the problem is while uploading something first i have to do
git add .
then git commit -m "commit message"
then push it like git push main...

is there any automation script that does that so that i can use that in terminal???

**Comment by parthasdey2304** [comment]
Well let me help you out with this is have got experience of bash scripting of 2 years and I use linux as my daily drive..........

**Comment by CodeBurnerProgramming** [comment]
Thanks!!
