### ISSUE TITLE
Add projects

### ISSUE THREAD

**Issue by EFFLUX110** [Sangwan5688/Hacktoberfest2021#832]
Hey 😊,
I want to add my `GARUDA port scanner project` for _hacktoberfest_ in this repository.
Please assign me for this.

**Comment by vaishnavisaindane** [comment]
I want to add my restaurants bill management project developed in php. @Sangwan5688 please assign it to me

**Comment by Sangwan5688** [comment]
You can add all projects and all anything you like without asking for permission. As for Hacktoberfest, sadly the project is now excluded from Hacktoberfest (#302), so your contributions will not be counted
